# Assignment-2 (ES 600)

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
ct=pd.read_excel("C:\\Users\\Supriya Mandal\\Desktop\\EVS correlation\\collection tank.xlsx")
gw=pd.read_excel("C:\\Users\\Supriya Mandal\\Desktop\\EVS correlation\\ground water.xlsx")

In [31]:
ct

,Unnamed: 0,PH,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
0,June,8.28,28.590,16600,8153.15,9600.0,4513,957.00,1120
1,June,8.07,20.330,15240,6500.00,8000.0,4356,749.00,1336
2,July,7.72,4.958,3460,1641.64,2887.0,4000,710.00,974
3,July,6.72,4.451,4600,5760.45,4035.0,3560,583.64,792
4,Aug,7.09,6.280,13840,11068.00,2376.0,1115,829.70,704
5,Aug,7.15,5.310,9430,9999.00,1108.8,680,689.70,859
6,Sept,7.19,4.900,9620,8230.00,1490.0,550,760.00,1533
7,Oct,7.56,4.802,8270,4986.00,3690.0,1256,750.00,890

In [32]:
gw

,Unnamed: 0,PH,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
0,June,7.26,0.896,670,215.20,23.00,7.5,280.00,190
1,June,6.85,0.747,490,165.17,25.00,8.0,170.00,380
2,July,7.27,0.771,720,170.17,16.47,8.0,395.00,17
3,July,6.74,0.707,480,747.87,18.60,7.0,89.11,19
4,Aug,6.97,0.829,490,11286.00,19.00,7.0,256.00,145
5,Aug,6.77,0.691,470,1089.00,15.84,6.5,268.00,270
6,Sept,6.75,0.790,490,730.00,15.00,6.0,210.00,170
7,Oct,6.88,0.670,450,190.00,16.00,7.0,255.00,225

In [33]:
ct.drop(['Unnamed: 0'],axis=1,inplace=True)
gw.drop(['Unnamed: 0'],axis=1,inplace=True)

In [34]:
ct

     PH  Conductivity    TDS  Alkalinity     COD   BOD  Chloride  Sulphate
0  8.28        28.590  16600     8153.15  9600.0  4513    957.00      1120
1  8.07        20.330  15240     6500.00  8000.0  4356    749.00      1336
2  7.72         4.958   3460     1641.64  2887.0  4000    710.00       974
3  6.72         4.451   4600     5760.45  4035.0  3560    583.64       792
4  7.09         6.280  13840    11068.00  2376.0  1115    829.70       704
5  7.15         5.310   9430     9999.00  1108.8   680    689.70       859
6  7.19         4.900   9620     8230.00  1490.0   550    760.00      1533
7  7.56         4.802   8270     4986.00  3690.0  1256    750.00       890

In [35]:
gw

     PH  Conductivity  TDS  Alkalinity    COD  BOD  Chloride  Sulphate
0  7.26         0.896  670      215.20  23.00  7.5    280.00       190
1  6.85         0.747  490      165.17  25.00  8.0    170.00       380
2  7.27         0.771  720      170.17  16.47  8.0    395.00        17
3  6.74         0.707  480      747.87  18.60  7.0     89.11        19
4  6.97         0.829  490    11286.00  19.00  7.0    256.00       145
5  6.77         0.691  470     1089.00  15.84  6.5    268.00       270
6  6.75         0.790  490      730.00  15.00  6.0    210.00       170
7  6.88         0.670  450      190.00  16.00  7.0    255.00       225

In [36]:
ct.rename(columns={'PH':'PH_ct'},inplace=True)
l_ct=list(ct.columns)
l_ct

['PH_ct',
 'Conductivity',
 'TDS',
 'Alkalinity',
 'COD',
 'BOD',
 'Chloride',
 'Sulphate']

In [37]:
# l_ct=list(ct.columns)
# l_ct

In [38]:
gw.rename(columns={'PH':'PH_gw'},inplace=True)
l_gw=list(gw.columns)
l_gw

['PH_gw',
 'Conductivity',
 'TDS',
 'Alkalinity',
 'COD',
 'BOD',
 'Chloride',
 'Sulphate']

#          #   Question-1

Determine correlation structures (in form of matrices) among quality parameters
separately for Collection tank (CT) and Groundwater (GW). For example: pH with
other parameters in CT and likewise in GW, etc

# CT (Question-1)

# Pearson Corellation Matrix for the table CT (Qn-1)

In [39]:
p_ct_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=ct.columns)

for ct_column in l_ct:
    for ct_column1 in l_ct:
         p_ct_correlation_matrix1.loc[ct_column, ct_column1] = ct[ct_column].corr(ct[ct_column1])



print("Correlation matrix between parameter of ct:")

print(type(p_ct_correlation_matrix1))

Correlation matrix between parameter of ct:
<class 'pandas.core.frame.DataFrame'>

In [57]:
print("\n")
print("           Pearson Corellation Matrix for the table CT               ")

print("\n")
print(" Pearson Correlation coefficient among the quality parameters for Collection tank (CT)")
p_ct_correlation_matrix1

           Pearson Corellation Matrix for the table CT


 Pearson Correlation coefficient among the quality parameters for Collection tank (CT)

,PH_ct,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,1.0,0.816274,0.537091,-0.251916,0.775987,0.594176,0.665568,0.420828
Conductivity,0.816274,1.0,0.771055,0.129878,0.932565,0.647093,0.699559,0.358518
TDS,0.537091,0.771055,1.0,0.631958,0.599884,0.103545,0.78483,0.287154
Alkalinity,-0.251916,0.129878,0.631958,1.0,-0.115176,-0.515648,0.358198,-0.065336
COD,0.775987,0.932565,0.599884,-0.115176,1.0,0.794459,0.520244,0.259938
BOD,0.594176,0.647093,0.103545,-0.515648,0.794459,1.0,0.119238,0.105568
Chloride,0.665568,0.699559,0.78483,0.358198,0.520244,0.119238,1.0,0.229522
Sulphate,0.420828,0.358518,0.287154,-0.065336,0.259938,0.105568,0.229522,1.0

In [61]:
# import matplotlib.pyplot as plt
# import pandas as pd
# import seaborn as sns

# # Correlation data
# data = {
#     "PH_ct": [1.0, 0.816274, 0.537091, -0.251916, 0.775987, 0.594176, 0.665568, 0.420828],
#     "Conductivity": [0.816274, 1.0, 0.771055, 0.129878, 0.932565, 0.647093, 0.699559, 0.358518],
#     "TDS": [0.537091, 0.771055, 1.0, 0.631958, 0.599884, 0.103545, 0.78483, 0.287154],
#     "Alkalinity": [-0.251916, 0.129878, 0.631958, 1.0, -0.115176, -0.515648, 0.358198, -0.065336],
#     "COD": [0.775987, 0.932565, 0.599884, -0.115176, 1.0, 0.794459, 0.520244, 0.259938],
#     "BOD": [0.594176, 0.647093, 0.103545, -0.515648, 0.794459, 1.0, 0.119238, 0.105568],
#     "Chloride": [0.665568, 0.699559, 0.78483, 0.358198, 0.520244, 0.119238, 1.0, 0.229522],
#     "Sulphate": [0.420828, 0.358518, 0.287154, -0.065336, 0.259938, 0.105568, 0.229522, 1.0]
# }

# # Create DataFrame
# df = pd.DataFrame(data)

# # Generate a mask for the upper triangle
# mask = np.triu(np.ones_like(df, dtype=bool))

# # Set up the matplotlib figure
# plt.figure(figsize=(10, 8))

# # Draw the heatmap with the mask
# sns.heatmap(df, mask=mask, cmap='coolwarm', annot=True, fmt=".2f", linewidths=0.5)

# plt.title('Correlation Matrix')
# plt.show()

In [60]:
# import matplotlib.pyplot as plt
# import pandas as pd
# import seaborn as sns

# # Correlation data
# data = {
#     "PH_ct": [1.0, 0.816274, 0.537091, -0.251916, 0.775987, 0.594176, 0.665568, 0.420828],
#     "Conductivity": [0.816274, 1.0, 0.771055, 0.129878, 0.932565, 0.647093, 0.699559, 0.358518],
#     "TDS": [0.537091, 0.771055, 1.0, 0.631958, 0.599884, 0.103545, 0.78483, 0.287154],
#     "Alkalinity": [-0.251916, 0.129878, 0.631958, 1.0, -0.115176, -0.515648, 0.358198, -0.065336],
#     "COD": [0.775987, 0.932565, 0.599884, -0.115176, 1.0, 0.794459, 0.520244, 0.259938],
#     "BOD": [0.594176, 0.647093, 0.103545, -0.515648, 0.794459, 1.0, 0.119238, 0.105568],
#     "Chloride": [0.665568, 0.699559, 0.78483, 0.358198, 0.520244, 0.119238, 1.0, 0.229522],
#     "Sulphate": [0.420828, 0.358518, 0.287154, -0.065336, 0.259938, 0.105568, 0.229522, 1.0]
# }

# # Create DataFrame
# df = pd.DataFrame(data)

# # Set up the matplotlib figure
# plt.figure(figsize=(10, 8))

# # Draw the heatmap
# sns.heatmap(df, cmap='viridis', annot=True, fmt=".2f", linewidths=0.5)

# plt.title('Correlation Matrix')
# plt.show()

# Sphereman Corellation between parameter of CT (Qu -1)

In [43]:
from scipy.stats import spearmanr

ct_spearman_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=ct.columns)

for ct_column in l_ct:
    for ct_column_1 in l_ct:
#         print(ct_column," ",gw_column)
#          aa = ct[ct_column].corr(gw[gw_column])
         ct_spearman_correlation_matrix1.loc[ct_column, ct_column_1],p_val = spearmanr(ct[ct_column],ct[ct_column_1])



print("Correlation matrix between ct :")

# print(correlation_matrix1['PH']['PH'])
# print('\n')
# print(ct_spearman_correlation_matrix1)

print(type(ct_spearman_correlation_matrix1))

Correlation matrix between ct :
<class 'pandas.core.frame.DataFrame'>

In [62]:
print("\n")
print("    Spearman Corellation Matrix among the quality parameter for Collection tank(CT)              ")
ct_spearman_correlation_matrix1

    Spearman Corellation Matrix among the quality parameter for Collection tank(CT)

,PH_ct,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,1.0,0.595238,0.428571,-0.333333,0.547619,0.666667,0.428571,0.714286
Conductivity,0.595238,1.0,0.809524,0.428571,0.285714,0.452381,0.547619,0.238095
TDS,0.428571,0.809524,1.0,0.595238,0.333333,0.238095,0.714286,0.333333
Alkalinity,-0.333333,0.428571,0.595238,1.0,-0.452381,-0.5,0.380952,-0.190476
COD,0.547619,0.285714,0.333333,-0.452381,1.0,0.904762,0.190476,0.214286
BOD,0.666667,0.452381,0.238095,-0.5,0.904762,1.0,0.095238,0.190476
Chloride,0.428571,0.547619,0.714286,0.380952,0.190476,0.095238,1.0,0.285714
Sulphate,0.714286,0.238095,0.333333,-0.190476,0.214286,0.190476,0.285714,1.0

# kendalltau Corellation between parameter of CT (Qu -1)

In [45]:
from scipy.stats import kendalltau

ct_kendalltau_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=ct.columns)

for ct_column in l_ct:
    for ct_column_1 in l_ct:
         ct_kendalltau_correlation_matrix1.loc[ct_column, ct_column_1],p_val = kendalltau(ct[ct_column],ct[ct_column_1])



print("Correlation matrix between ct and gw:")

print(type(ct_kendalltau_correlation_matrix1))

Correlation matrix between ct and gw:
<class 'pandas.core.frame.DataFrame'>

In [59]:
print("\n")
print("Kendall’s tau Corellation Matrix among the quality parameter for Collection tank(CT)           ")
ct_kendalltau_correlation_matrix1

Kendall’s tau Corellation Matrix among the quality parameter for Collection tank(CT)

,PH_ct,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,1.0,0.428571,0.285714,-0.285714,0.428571,0.5,0.285714,0.571429
Conductivity,0.428571,1.0,0.714286,0.285714,0.142857,0.357143,0.428571,0.142857
TDS,0.285714,0.714286,1.0,0.428571,0.285714,0.071429,0.571429,0.142857
Alkalinity,-0.285714,0.285714,0.428571,1.0,-0.142857,-0.214286,0.285714,-0.142857
COD,0.428571,0.142857,0.285714,-0.142857,1.0,0.785714,0.142857,0.142857
BOD,0.5,0.357143,0.071429,-0.214286,0.785714,1.0,0.071429,0.214286
Chloride,0.285714,0.428571,0.571429,0.285714,0.142857,0.071429,1.0,0.285714
Sulphate,0.571429,0.142857,0.142857,-0.142857,0.142857,0.214286,0.285714,1.0

# GW (Question-1)

# Pearson Corellation Matrix for the table GW (Qn-1)

In [50]:
p_gw_correlation_matrix1 = pd.DataFrame(index=gw.columns, columns=gw.columns)

for gw_column in l_gw:
    for gw_column_1 in l_gw:
         p_gw_correlation_matrix1.loc[gw_column, gw_column_1] = gw[gw_column].corr(gw[gw_column_1])



print("Correlation matrix between parameter of gw:")

print(type(p_gw_correlation_matrix1))

Correlation matrix between parameter of gw:
<class 'pandas.core.frame.DataFrame'>

In [53]:
print("\n")
print(" Pearson Correlation coefficient among the quality parameters for Groundwater (GW)           ")
p_gw_correlation_matrix1.head(10)

 Pearson Correlation coefficient among the quality parameters for Groundwater (GW)

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_gw,1.0,0.631695,0.920604,0.003203,0.263268,0.64434,0.747676,-0.290068
Conductivity,0.631695,1.0,0.585041,0.324365,0.434377,0.18459,0.275083,-0.114847
TDS,0.920604,0.585041,1.0,-0.211126,0.175923,0.579413,0.6771,-0.420949
Alkalinity,0.003203,0.324365,-0.211126,1.0,-0.001766,-0.142322,0.04052,-0.111425
COD,0.263268,0.434377,0.175923,-0.001766,1.0,0.647771,-0.266924,0.42861
BOD,0.64434,0.18459,0.579413,-0.142322,0.647771,1.0,0.278788,0.016882
Chloride,0.747676,0.275083,0.6771,0.04052,-0.266924,0.278788,1.0,-0.153128
Sulphate,-0.290068,-0.114847,-0.420949,-0.111425,0.42861,0.016882,-0.153128,1.0

# Sphereman Corellation between parameter of GW (Qu -1)

In [63]:
from scipy.stats import spearmanr

gw_spearman_correlation_matrix1 = pd.DataFrame(index=gw.columns, columns=gw.columns)

for gw_column in l_gw:
    for gw_column_1 in l_gw:
         gw_spearman_correlation_matrix1.loc[gw_column, gw_column_1],p_val = spearmanr(gw[gw_column],gw[gw_column_1])
print("Correlation matrix between gw :")
print(type(gw_spearman_correlation_matrix1))

Correlation matrix between gw :
<class 'pandas.core.frame.DataFrame'>

In [67]:
print("\n")
print("  Spearman Corellation Matrix among the quality parameter for Groundwater(GW)        ")
gw_spearman_correlation_matrix1

  Spearman Corellation Matrix among the quality parameter for Groundwater(GW)

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_gw,1.0,0.428571,0.609938,-0.333333,0.357143,0.638337,0.809524,-0.190476
Conductivity,0.428571,1.0,0.805118,0.119048,0.380952,0.184136,0.333333,-0.333333
TDS,0.609938,0.805118,1.0,-0.317168,0.39036,0.566049,0.48795,-0.439155
Alkalinity,-0.333333,0.119048,-0.317168,1.0,-0.285714,-0.699716,-0.02381,-0.214286
COD,0.357143,0.380952,0.39036,-0.285714,1.0,0.761094,-0.071429,0.119048
BOD,0.638337,0.184136,0.566049,-0.699716,0.761094,1.0,0.245514,-0.061379
Chloride,0.809524,0.333333,0.48795,-0.02381,-0.071429,0.245514,1.0,-0.190476
Sulphate,-0.190476,-0.333333,-0.439155,-0.214286,0.119048,-0.061379,-0.190476,1.0

# kendalltau Corellation between parameter of GW (Qu -1)

In [69]:
from scipy.stats import kendalltau

gw_kendalltau_correlation_matrix1 = pd.DataFrame(index=gw.columns, columns=gw.columns)

for gw_column in l_gw:
    for gw_column_1 in l_gw:
         gw_kendalltau_correlation_matrix1.loc[gw_column, gw_column_1],p_val = kendalltau(gw[gw_column],gw[gw_column_1])
print("Correlation matrix between ct and gw:")
print(type(gw_kendalltau_correlation_matrix1))

Correlation matrix between ct and gw:
<class 'pandas.core.frame.DataFrame'>

In [72]:
print("\n")
print("   Kendall’s tau Corellation Matrix among the quality parameter for Groundwater           ")
gw_kendalltau_correlation_matrix1

   Kendall’s tau Corellation Matrix among the quality parameter for Groundwater

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_gw,1.0,0.285714,0.491354,-0.214286,0.285714,0.540062,0.714286,-0.142857
Conductivity,0.285714,1.0,0.718132,0.071429,0.285714,0.154303,0.285714,-0.142857
TDS,0.491354,0.718132,1.0,-0.264575,0.264575,0.449073,0.415761,-0.264575
Alkalinity,-0.214286,0.071429,-0.264575,1.0,-0.214286,-0.540062,-0.071429,-0.214286
COD,0.285714,0.285714,0.264575,-0.214286,1.0,0.694365,0.0,0.142857
BOD,0.540062,0.154303,0.449073,-0.540062,0.694365,1.0,0.231455,-0.077152
Chloride,0.714286,0.285714,0.415761,-0.071429,0.0,0.231455,1.0,-0.142857
Sulphate,-0.142857,-0.142857,-0.264575,-0.214286,0.142857,-0.077152,-0.142857,1.0

# #  Question-2

Determine the correlation between each quality parameter of leachate
(in CT) with GW. For example: pH of CT with GW, etc.

# Pearson Corellation between parameter of CT and parameter of GW (Question -2)

In [73]:
p_ct_gw_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=gw.columns)

for ct_column in l_ct:
    for gw_column in l_gw:
         p_ct_gw_correlation_matrix1.loc[ct_column, gw_column] = ct[ct_column].corr(gw[gw_column])



print(" Pearson Correlation matrix between ct and gw:")
# print(correlation_matrix1)
print(type(p_ct_gw_correlation_matrix1))

 Pearson Correlation matrix between ct and gw:
<class 'pandas.core.frame.DataFrame'>

In [82]:
print("\n")
print("  Pearson Correlation between each quality parameters of leachate in CT with GW              ")
p_ct_gw_correlation_matrix1

  Pearson Correlation between each quality parameters of leachate in CT with GW

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,0.65605,0.4415,0.560589,-0.357753,0.620328,0.655662,0.41409,0.440355
Conductivity,0.458828,0.616386,0.387781,-0.203067,0.859953,0.491648,-0.006843,0.443003
TDS,0.131154,0.58648,-0.066131,0.289494,0.700869,0.108637,-0.090749,0.682594
Alkalinity,-0.35302,0.290423,-0.469658,0.588315,0.097608,-0.552634,-0.257254,0.394923
COD,0.430033,0.451055,0.352067,-0.289195,0.894857,0.637025,-0.141611,0.322311
BOD,0.554736,0.31645,0.624829,-0.372844,0.724879,0.8484,-0.009292,-0.117548
Chloride,0.591904,0.809469,0.383692,0.240958,0.418165,0.150109,0.393122,0.291627
Sulphate,-0.086938,0.247198,0.07889,-0.467576,0.18875,-0.085473,-0.099989,0.386876

# Sphereman Corellation between parameter of CT and parameter of GW (Question -2)

In [84]:
from scipy.stats import spearmanr

spearman_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=gw.columns)

for ct_column in l_ct:
    for gw_column in l_gw:
         spearman_correlation_matrix1.loc[ct_column, gw_column],p_val = spearmanr(ct[ct_column],gw[gw_column])

print("Sphereman Correlation matrix between ct and gw:")
print(type(spearman_correlation_matrix1))

Sphereman Correlation matrix between ct and gw:
<class 'pandas.core.frame.DataFrame'>

In [88]:
print("\n")
print(" Spearman Correlation between each quality parameters of leachate in CT with GW                ")
spearman_correlation_matrix1
# Spearman

 Spearman Correlation between each quality parameters of leachate in CT with GW

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,0.595238,0.285714,0.512348,-0.785714,0.380952,0.626061,0.404762,0.357143
Conductivity,0.52381,0.595238,0.512348,-0.119048,0.619048,0.42965,0.428571,0.404762
TDS,0.119048,0.571429,0.219578,0.02381,0.52381,0.073654,-0.02381,0.547619
Alkalinity,-0.214286,0.380952,-0.09759,0.738095,-0.047619,-0.552407,0.0,0.261905
COD,0.238095,0.190476,0.268373,-0.547619,0.785714,0.699716,-0.166667,0.095238
BOD,0.5,0.238095,0.48795,-0.619048,0.809524,0.896127,0.166667,0.02381
Chloride,0.47619,0.714286,0.365963,0.02381,0.238095,0.012276,0.285714,0.095238
Sulphate,0.02381,0.238095,0.39036,-0.666667,-0.047619,0.147309,-0.02381,0.309524

# Kendalltau Corellation between parameter of CT and parameter of GW (Question -2)

In [89]:
from scipy.stats import kendalltau

kendalltau_correlation_matrix1 = pd.DataFrame(index=ct.columns, columns=gw.columns)

for ct_column in l_ct:
    for gw_column in l_gw:
         kendalltau_correlation_matrix1.loc[ct_column, gw_column],p_val = kendalltau(ct[ct_column],gw[gw_column])

            
print("Correlation matrix between ct and gw:")
print(type(kendalltau_correlation_matrix1))

Correlation matrix between ct and gw:
<class 'pandas.core.frame.DataFrame'>

In [91]:
print("\n")
print("Kendall’s tau Correlation between each quality parameters of leachate in CT with GW              ")
kendalltau_correlation_matrix1

Kendall’s tau Correlation between each quality parameters of leachate in CT with GW

,PH_gw,Conductivity,TDS,Alkalinity,COD,BOD,Chloride,Sulphate
PH_ct,0.428571,0.142857,0.340168,-0.642857,0.285714,0.385758,0.285714,0.285714
Conductivity,0.428571,0.428571,0.415761,-0.071429,0.428571,0.308607,0.285714,0.285714
TDS,0.142857,0.428571,0.264575,0.071429,0.285714,0.0,0.0,0.428571
Alkalinity,-0.142857,0.285714,-0.037796,0.642857,0.0,-0.385758,0.0,0.142857
COD,0.142857,0.142857,0.264575,-0.357143,0.571429,0.540062,-0.142857,0.0
BOD,0.357143,0.214286,0.340168,-0.428571,0.642857,0.771517,0.071429,-0.071429
Chloride,0.428571,0.571429,0.264575,0.071429,0.142857,0.0,0.285714,0.0
Sulphate,0.0,0.142857,0.113389,-0.5,0.0,0.154303,0.0,0.142857